eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/


spring:
  application:
    name: resource-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
feign:
  hystrix:
    enabled: true

server:
  port: 9090